Update MySQL-python version to 1.2.5 in Part 1 branch
required version Mysql-python 1.2.5 and you will get this error with the previous version

EnvironmentError: mysql_config not found

----------------------------------------
Command python setup.py egg_info failed with error code 1
Storing complete log in /home/zjm1126/.pip/pip.log